-- Create journey_log_entries table for storing detailed journey log form data
CREATE TABLE IF NOT EXISTS `journey_log_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pilot_name` varchar(255) NOT NULL,
  `log_date` date NOT NULL,
  `leg_number` int(11) DEFAULT NULL,
  `flight_no` varchar(50) DEFAULT NULL,
  `pc_fo` varchar(255) DEFAULT NULL,
  `pfc` varchar(50) DEFAULT NULL,
  `from_airport` varchar(10) DEFAULT NULL,
  `to_airport` varchar(10) DEFAULT NULL,
  `ofb_time` time DEFAULT NULL,
  `onb_time` time DEFAULT NULL,
  `block_time` varchar(20) DEFAULT NULL,
  `atd_time` time DEFAULT NULL,
  `ata_time` time DEFAULT NULL,
  `air_time` varchar(20) DEFAULT NULL,
  `legs` int(11) DEFAULT NULL,
  `fuel_uplift` varchar(20) DEFAULT NULL,
  `fuel_off` varchar(20) DEFAULT NULL,
  `fuel_on` varchar(20) DEFAULT NULL,
  `fuel_used` varchar(20) DEFAULT NULL,
  `fluid_type` varchar(50) DEFAULT NULL,
  `mixture` varchar(50) DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `eng1_oil` varchar(20) DEFAULT NULL,
  `eng2_oil` varchar(20) DEFAULT NULL,
  `eng3_oil` varchar(20) DEFAULT NULL,
  `apu_oil` varchar(20) DEFAULT NULL,
  `fault` enum('yes','no') DEFAULT 'no',
  `rvsm` enum('yes','no') DEFAULT 'no',
  `rnps` enum('yes','no') DEFAULT 'no',
  `next_inspection_type` varchar(100) DEFAULT NULL,
  `next_inspection_due` date DEFAULT NULL,
  `at_tt` varchar(50) DEFAULT NULL,
  `at_rc` varchar(50) DEFAULT NULL,
  `total_this_day` varchar(20) DEFAULT NULL,
  `carried_forward` varchar(20) DEFAULT NULL,
  `total_to_report` varchar(20) DEFAULT NULL,
  `correction` varchar(20) DEFAULT NULL,
  `technical_remarks` text DEFAULT NULL,
  `actions_taken` text DEFAULT NULL,
  `sign_auth` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pilot_date` (`pilot_name`, `log_date`),
  KEY `idx_log_date` (`log_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
