-- Recency Items Table
CREATE TABLE IF NOT EXISTS `recency_items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) DEFAULT NULL COMMENT 'HEAD, TIME, COMPOSITE, or empty for Item',
  `name` VARCHAR(200) NOT NULL,
  `departments` JSON DEFAULT NULL COMMENT 'Array of department names',
  `pilot_licence` VARCHAR(100) DEFAULT NULL,
  `type_specific` TINYINT(1) DEFAULT 0,
  `target_count` INT(11) DEFAULT 0,
  `months_apart` INT(11) DEFAULT 0,
  `increment_target` TINYINT(1) DEFAULT 0,
  `period` INT(11) DEFAULT 0,
  `period_type` ENUM('D', 'M', 'NA') DEFAULT 'D' COMMENT 'Days, Months, or Not Available',
  `warning` INT(11) DEFAULT 0 COMMENT 'Caution in weeks',
  `renewal` INT(11) DEFAULT 0,
  `renewal_type` ENUM('D', 'M') DEFAULT 'D',
  `renewal_count_type` ENUM('D', 'M') DEFAULT 'D' COMMENT 'To The Day or Calendar Month',
  `grace_period` INT(11) DEFAULT 0,
  `grace_period_type` ENUM('D', 'M') DEFAULT 'D',
  `reval` INT(11) DEFAULT 0 COMMENT 'Re-validation required after (months)',
  `end_period` VARCHAR(10) DEFAULT NULL COMMENT 'EOM, EOQ, EOT, EOY, or empty',
  `default_status` ENUM('Required', 'Optional', 'Hidden') DEFAULT 'Optional',
  `contacts` TEXT DEFAULT NULL,
  `disabled` TINYINT(1) DEFAULT 0,
  `documentation_type` ENUM('File Upload', 'Link to a repository') DEFAULT 'File Upload',
  `document_required` TINYINT(1) DEFAULT 0,
  `created_by` INT(11) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_type` (`type`),
  KEY `idx_name` (`name`),
  KEY `idx_disabled` (`disabled`),
  KEY `idx_created_by` (`created_by`),
  FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Recency items configuration';

