-- Safety Reports Table
CREATE TABLE `safety_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `report_type` varchar(100) NOT NULL,
  `report_no` varchar(50) DEFAULT NULL,
  `submit_on_behalf_of` varchar(255) DEFAULT NULL,
  `reporter_name` varchar(255) NOT NULL,
  `reporter_address_line_1` varchar(255) DEFAULT NULL,
  `reporter_address_line_2` varchar(255) DEFAULT NULL,
  `reporter_suburb` varchar(100) DEFAULT NULL,
  `reporter_state` varchar(100) DEFAULT NULL,
  `reporter_postcode` varchar(20) DEFAULT NULL,
  `reporter_country` varchar(100) DEFAULT NULL,
  `reporter_telephone` varchar(20) DEFAULT NULL,
  `reporter_fax` varchar(20) DEFAULT NULL,
  `reporter_email` varchar(100) DEFAULT NULL,
  `confidential` tinyint(1) DEFAULT 0,
  `report_title` varchar(255) NOT NULL,
  `event_date_time` datetime DEFAULT NULL,
  `event_base` varchar(255) DEFAULT NULL,
  `event_department` varchar(255) DEFAULT NULL,
  `report_description` text DEFAULT NULL,
  `status` enum('draft','submitted','under_review','resolved','closed') DEFAULT 'draft',
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_status` (`status`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_event_date_time` (`event_date_time`),
  KEY `idx_report_no` (`report_no`),
  CONSTRAINT `safety_reports_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Safety Reports for Raimon Fleet Management System';

