USE raimon_fleet;

-- Stations Table
CREATE TABLE IF NOT EXISTS `stations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `station_name` varchar(255) NOT NULL,
  `iata_code` varchar(10) NOT NULL,
  `status` enum('active', 'inactive', 'maintenance') DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `iata_code` (`iata_code`),
  KEY `idx_status` (`status`),
  KEY `idx_station_name` (`station_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert Iranian airports data
INSERT INTO `stations` (`id`, `station_name`, `iata_code`, `status`) VALUES
(12, 'Abadan Airport', 'OIAA', 'active'),
(150, 'Abumusa Airport', 'OIBA', 'active'),
(146, 'Aghajari Airport', 'OIAG', 'active'),
(52, 'Ahvaz International Airport', 'OIAW', 'active'),
(168, 'Arak Airport', 'OIHR', 'active'),
(21, 'Ardabil Airport', 'OITL', 'active'),
(48, 'Asaluyeh Airport', 'OIBP', 'active'),
(44, 'Astrakhan Narimanovo Airport', 'URWA', 'active'),
(152, 'Bahregan Airport', 'OIBH', 'active'),
(177, 'Bam Airport', 'OIKM', 'active'),
(178, 'Bandar Abbas / Havadarya Airport', 'OIKP', 'active'),
(47, 'Bandar Abbas Airport', 'OIKB', 'active'),
(154, 'Bandar Lengeh Airport', 'OIBL', 'active'),
(180, 'Birjand Airport', 'OIMB', 'active'),
(189, 'Bisheh kola Airport', 'OINJ', 'active'),
(184, 'Bojnord Airport', 'OIMN', 'active'),
(151, 'Bushehr Airport', 'OIBB', 'active'),
(50, 'Chabahar Airport', 'OIZC', 'active'),
(145, 'Dezful Airport', 'OIAD', 'active'),
(42, 'Dushanbe International Airport', 'UTDD', 'active'),
(166, 'Esfahan Badr Airport', 'OIFP', 'active'),
(163, 'Esfahan/ Hesa Airport', 'OIFE', 'active'),
(164, 'Esfahan/ ShahidvatanpourAirport', 'OIFH', 'active'),
(170, 'Eyvanaki Boland Parvaz Airport', 'OIIB', 'active'),
(192, 'Fasa Airport', 'OISF', 'active'),
(147, 'Gachsaran Airport', 'OIAH', 'active'),
(173, 'Ghazvin Airport', 'OIIK', 'active'),
(20, 'Gorgan Airport', 'OING', 'active'),
(167, 'Hamadan Airport', 'OIHH', 'active'),
(169, 'Hamadan Nogeh Airport', 'OIHS', 'active'),
(160, 'Ilam Airport', 'OICI', 'active'),
(205, 'Iran Shahr', 'OIZI', 'active'),
(5, 'Isfahan International Airport', 'OIFM', 'active'),
(193, 'Jahrom Airport', 'OISJ', 'active'),
(153, 'Jam Airport', 'OIBJ', 'active'),
(176, 'Jiroft Airport', 'OIKJ', 'active'),
(188, 'Kalaleh Airport', 'OINE', 'active'),
(172, 'Karaj / Fath Airport', 'OIIF', 'active'),
(174, 'Karaj /Naja Airport', 'OIIM', 'active'),
(165, 'Kashan Airport', 'OIFK', 'active'),
(185, 'Kashmar Airport', 'OIMQ', 'active'),
(13, 'Kerman Airport', 'OIKK', 'active'),
(159, 'Kermanshah Airport', 'OICC', 'active'),
(155, 'Khark Airport', 'OIBQ', 'active'),
(161, 'Khoram Abad Airport', 'OICK', 'active'),
(197, 'Khoy Airport', 'OITK', 'active'),
(9, 'Kish International Airport', 'OIBK', 'active'),
(196, 'Lamerd Airport', 'OISR', 'active'),
(194, 'Lar Airport', 'OISL', 'active'),
(157, 'Lavan Airport', 'OIBV', 'active'),
(53, 'Mahshahr Airport', 'OIAM', 'active'),
(201, 'Maku Airport', 'OITU', 'active'),
(198, 'Maragheh Airport', 'OITM', 'active'),
(25, 'Mashhad International Airport', 'OIMM', 'active'),
(182, 'Mashhad/ Golbahar l Airport', 'OIMG', 'active'),
(148, 'Masjed Soleiman', 'OIAI', 'active'),
(32, 'Mehrabad International Airport', 'OIII', 'active'),
(203, 'Mehriz /Imam Reza Airport', 'OIYR', 'active'),
(190, 'Noshahr Airport', 'OINN', 'active'),
(149, 'Omidiyeh Airport', 'OIAJ', 'active'),
(199, 'Parsabad Moghan Airport', 'OITP', 'active'),
(41, 'Payam Airport', 'OIIP', 'active'),
(51, 'Qeshm Dayrestan Airport', 'OIKQ', 'active'),
(179, 'Rafsanjan Airport', 'OIKR', 'active'),
(191, 'Ramsar Airport', 'OINR', 'active'),
(39, 'Rasht International Airport', 'OIGG', 'active'),
(186, 'Sabzevar Airport', 'OIMS', 'active'),
(162, 'Sanandaj Airport', 'OICS', 'active'),
(181, 'Sarakhs Airport', 'OIMC', 'active'),
(206, 'Saravan Airport', 'OIZS', 'active'),
(24, 'Sari Airport', 'OINZ', 'active'),
(175, 'Semnan Airport', 'OIIS', 'active'),
(40, 'Shahrekord Airport', 'OIFS', 'active'),
(183, 'Shahroud Airport', 'OIMJ', 'active'),
(34, 'Shiraz International Airport', 'OISS', 'active'),
(156, 'Siri Airport', 'OIBS', 'active'),
(54, 'Sirjan Airport', 'OIKY', 'active'),
(187, 'Tabas Airport', 'OIMT', 'active'),
(36, 'Tabriz International Airport', 'OITT', 'active'),
(171, 'Tehran Doshan Tappeh Airport', 'OIID', 'active'),
(1, 'Tehran Imam Khomeini International', 'OIIE', 'active'),
(158, 'Tonbe-Bozorg Airport', 'OIBX', 'active'),
(200, 'Uromiyeh Airport', 'OITR', 'active'),
(14, 'Yasouj Airport', 'OISY', 'active'),
(202, 'Yazd / Pardis Airport', 'OIYP', 'active'),
(49, 'Yazd Airport', 'OIYY', 'active'),
(204, 'Zabol Airport', 'OIZB', 'active'),
(37, 'Zahedan International Airport', 'OIZH', 'active'),
(16, 'Zanjan Airport', 'OITZ', 'active'),
(195, 'Zarghan Airport', 'OISO', 'active');

